"""
Project paths, constants, and persisted portal URL for MAHACET FE scrapers.

The active portal URL is written by ``scraper/url_discovery.py`` to
``config/discovered_portal_url.json`` and read at runtime by scrapers.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

PROJECT_ROOT: Path = Path(__file__).resolve().parents[1]
DATA_DIR: Path = PROJECT_ROOT / "data"
CONFIG_DIR: Path = PROJECT_ROOT / "config"
SCRAPER_DIR: Path = PROJECT_ROOT / "scraper"
CLEANER_DIR: Path = PROJECT_ROOT / "cleaner"
MODEL_DIR: Path = PROJECT_ROOT / "model"
APP_DIR: Path = PROJECT_ROOT / "app"
TESTS_DIR: Path = PROJECT_ROOT / "tests"

DISCOVERED_URL_FILE: Path = CONFIG_DIR / "discovered_portal_url.json"
# Auto-generated Python snippet (importable by scrapers without JSON parsing).
DISCOVERED_RUNTIME_PY: Path = CONFIG_DIR / "discovered_runtime.py"
URL_DISCOVERY_LOG: Path = DATA_DIR / "Data_Quality_Logs" / "url_discovery_log.json"
CLEANING_SUMMARY_FILE: Path = DATA_DIR / "Data_Quality_Logs" / "cleaning_summary.json"
MASTER_COLLEGE_LIST: Path = DATA_DIR / "College_Details" / "master_college_list.csv"
MODEL_ARTIFACTS_DIR: Path = MODEL_DIR / "model_artifacts"
MODEL_PKL: Path = MODEL_ARTIFACTS_DIR / "model.pkl"
FEATURES_JSON: Path = MODEL_ARTIFACTS_DIR / "features.json"

# Admission cycle year (calendar year in portal hostname). Override with env MAHA_FE_YEAR.
ADMISSION_PORTAL_YEAR: int = int(os.environ.get("MAHA_FE_YEAR", "") or 0) or datetime.now().year

PRIMARY_PORTAL_TEMPLATE: str = "https://fe{year}.mahacet.org/StaticPages/HomePage"

SEARCH_QUERIES_TEMPLATE: list[str] = [
    "mahacet.org FE admission {year} official portal",
    "Maharashtra First Year Engineering CAP {year} site",
    "MAHACET FE CET CELL official website {year}",
]

# Page validation: these substrings should appear on a genuine FE portal page.
PORTAL_CONTENT_MARKERS: tuple[str, ...] = (
    "CAP",
    "Merit",
    "CET",
)

REQUEST_TIMEOUT_SEC: int = int(os.environ.get("MAHA_FE_HTTP_TIMEOUT", "60"))
MAX_HTTP_RETRIES: int = int(os.environ.get("MAHA_FE_HTTP_RETRIES", "3"))
SCRAPER_DELAY_MIN_SEC: float = float(os.environ.get("MAHA_FE_DELAY_MIN", "2.0"))
SCRAPER_DELAY_MAX_SEC: float = float(os.environ.get("MAHA_FE_DELAY_MAX", "3.0"))

# Logging: set MAHA_LOG_LEVEL=WARNING in production to reduce noise.
LOG_LEVEL: str = os.environ.get("MAHA_LOG_LEVEL", "INFO").upper()

# Optional: Google Custom Search (never hardcode keys; use env only)
GOOGLE_CSE_API_KEY: str | None = os.environ.get("GOOGLE_CSE_API_KEY")
GOOGLE_CSE_CX: str | None = os.environ.get("GOOGLE_CSE_CX")


def default_portal_url(year: int | None = None) -> str:
    """Return the canonical guessed portal URL for a given admission cycle year."""
    y = year if year is not None else ADMISSION_PORTAL_YEAR
    return PRIMARY_PORTAL_TEMPLATE.format(year=y)


def load_discovered_portal_meta() -> dict[str, Any]:
    """Load persisted discovery metadata (url, validated_at, source)."""
    if not DISCOVERED_URL_FILE.is_file():
        return {}
    try:
        with DISCOVERED_URL_FILE.open(encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("Could not read %s: %s", DISCOVERED_URL_FILE, exc)
        return {}


def get_confirmed_portal_url(fallback_year: int | None = None) -> str | None:
    """Return last confirmed URL from disk, if any."""
    meta = load_discovered_portal_meta()
    url = meta.get("confirmed_url")
    if isinstance(url, str) and url.startswith("http"):
        return url
    return None


def save_discovered_portal_meta(meta: dict[str, Any]) -> None:
    """Write discovery result for other modules."""
    DISCOVERED_URL_FILE.parent.mkdir(parents=True, exist_ok=True)
    with DISCOVERED_URL_FILE.open("w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)
    logger.info("Saved portal metadata to %s", DISCOVERED_URL_FILE)
    url = meta.get("confirmed_url")
    if isinstance(url, str) and url.startswith("http"):
        write_discovered_runtime_py(url, int(meta.get("year", ADMISSION_PORTAL_YEAR) or ADMISSION_PORTAL_YEAR))


def write_discovered_runtime_py(confirmed_url: str, year: int) -> None:
    """
    Persist the confirmed portal URL as an importable module (prompt: consumable from ``settings``).

    This file is auto-generated; do not hand-edit. Git may ignore it — JSON remains the source of truth.
    """
    DISCOVERED_RUNTIME_PY.parent.mkdir(parents=True, exist_ok=True)
    url_lit = json.dumps(str(confirmed_url), ensure_ascii=False)
    body = (
        "# -*- coding: utf-8 -*-\n"
        '"""Auto-generated by url_discovery — do not edit by hand."""\n\n'
        f"CONFIRMED_PORTAL_URL: str = {url_lit}\n"
        f"DISCOVERY_YEAR: int = {int(year)}\n"
    )
    DISCOVERED_RUNTIME_PY.write_text(body, encoding="utf-8")
    logger.info("Wrote runtime portal module %s", DISCOVERED_RUNTIME_PY)


def get_active_portal_url(year: int | None = None) -> str:
    """
    Return the best-known portal homepage URL.

    Order: importable ``discovered_runtime`` → JSON meta → canonical template.
    """
    try:
        from config import discovered_runtime  # type: ignore[import-not-found]

        u = getattr(discovered_runtime, "CONFIRMED_PORTAL_URL", "")
        if isinstance(u, str) and u.startswith("http"):
            return u
    except ImportError:
        pass
    saved = get_confirmed_portal_url(year)
    if saved:
        return saved
    return default_portal_url(year)
